<script lang="ts">
	import 'carbon-components-svelte/css/white.css';
	import '../another.css';
	import { page } from '$app/stores';
	import { onMount } from 'svelte';
	import hljs from 'highlight.js';

	let lang = $page.url.searchParams.get('lang');
	let language = `language-${lang}`;
	let code = $page.url.searchParams.get('code');
	let theme = $page.url.searchParams.get('theme');

	onMount(() => {
		let codeTag = document.getElementById('code');

		const elem = hljs.highlightAuto(code!, [lang!]);
		codeTag!.innerHTML = elem.value;
	});
</script>

<svelte:head>
	<link
		rel="stylesheet"
		href={`//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/${theme}.min.css`}
	/>
</svelte:head>
<div class="written">
	generated by <a href="https://github.com/u-yas/highlight.embed"
		>github.com/u-yas/highlight-embed</a
	>
</div>
<div class="code-wrapper">
	<pre><code id="code" class={`${language} hljs`} />
    </pre>
</div>

<style>
	.written {
		position: absolute;
		bottom: 0;
		right: 0;
		padding: 0.5rem;
		font-size: 1rem;
		color: gray;
	}
	.code-wrapper {
		height: 100vh;
	}
	.code-wrapper pre {
		height: 100%;
		overflow: auto;
	}
	.code-wrapper pre code {
		height: 100%;
		overflow: auto;
	}
	pre {
		height: 100%;
	}
	code {
		display: block;
		text-indent: 0;
		overflow-x: auto;
		height: 100%;
		padding: 1rem;
		font-family: 'Roboto Mono', monospace;
		font-size: 1rem;
	}
	@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap');
</style>
